/**
 * Downloads the web fonts used by the app from Google Fonts and stores them in
 * `public/fonts/`, generating `src/fonts.css` with local `@font-face` rules.
 *
 * Self-hosting keeps visitor IP addresses away from third-party servers (the app
 * advertises "no tracking"), removes a render-blocking external dependency, and
 * makes the build reproducible.
 *
 * Run with: npm run fonts
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Only the subsets the UI actually needs. Cairo covers Arabic including the
// Presentation Forms-B block (U+FE70–U+FEFC) that the converter emits.
const FAMILIES = [
  { name: 'Cairo', css: 'family=Cairo:wght@400..700', subsets: ['arabic', 'latin'] },
  { name: 'Inter', css: 'family=Inter:wght@400..700', subsets: ['latin'] },
];

/**
 * Fonts live under `src/` rather than `public/` so Vite resolves, fingerprints
 * and cache-busts them. Referencing them relative to the generated stylesheet
 * also keeps them working whatever `base` the site is deployed under.
 */
const OUT_DIR = 'src/assets/fonts';

const curl = (url, out) =>
  execFileSync('curl', ['-sSfL', '-A', UA, url, ...(out ? ['-o', out] : [])], {
    maxBuffer: 64 * 1024 * 1024,
  });

mkdirSync(OUT_DIR, { recursive: true });

let css =
  '/* Self-hosted web fonts. Generated by `npm run fonts` — do not edit by hand. */\n\n';

for (const family of FAMILIES) {
  const sheet = curl(
    `https://fonts.googleapis.com/css2?${family.css}&display=swap`
  ).toString();

  // Google returns one `/* subset */ @font-face {...}` block per subset.
  const blocks = sheet.matchAll(/\/\* ([a-z0-9-]+) \*\/\s*(@font-face \{[^}]*\})/g);
  const seen = new Set();

  for (const [, subset, block] of blocks) {
    if (!family.subsets.includes(subset)) continue;

    const remote = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1];
    if (!remote || seen.has(remote)) continue;
    seen.add(remote);

    const file = `${family.name.toLowerCase()}-${subset}.woff2`;
    curl(remote, `${OUT_DIR}/${file}`);

    css +=
      `/* ${family.name} — ${subset} */\n` +
      block
        .replace(remote, `./assets/fonts/${file}`)
        // These are variable fonts: one file serves the whole weight range.
        .replace(/font-weight:\s*\d+;/, 'font-weight: 400 700;') +
      '\n\n';

    console.log(`  ${file}`);
  }
}

writeFileSync('src/fonts.css', css);
console.log('wrote src/fonts.css');
